In [ ]:
# pip install --upgrade ipywidgets
# pip install realtabformer
# pip install datasets==2.6.1

In [1]:
import os
import pandas as pd
from pathlib import Path
from datetime import datetime
import sys
sys.path.insert(0, '/home/yjung/SynPriv')
from src.realtabformer import REaLTabFormer
import warnings
warnings.filterwarnings("ignore")
device = 'cuda:3'

exp_name = "rtf_retail"
sample_sizes = [5000, 10000]
data_path = Path("../data/sampled")
base_save_dir = Path(f"../results/{exp_name}")
join_on = "fkey"
n_samples = 1000  # 생성할 메타 테이블 샘플 수

def run_rtf(sample_size):
    sub_exp_name = f"train{sample_size}"
    save_dir = base_save_dir / sub_exp_name
    save_dir.mkdir(parents=True, exist_ok=True)

    meta_path = data_path / f"retail_sample_{sample_size}_meta.csv"
    flow_path = data_path / f"retail_sample_{sample_size}_flow.csv"
    parent_df = pd.read_csv(meta_path)
    child_df = pd.read_csv(flow_path)

    print(f"{sample_size} parent 학습")
    parent_model = REaLTabFormer(model_type="tabular", epochs=10)
    parent_model.fit(parent_df.drop(columns=[join_on]), device=device)
    parent_model_dir = save_dir / "rtf_parent"
    parent_model.save(parent_model_dir)

    print(f"{sample_size} child 학습")
    parent_model_path = sorted(parent_model_dir.glob("id*"), key=os.path.getmtime)[-1]
    child_model = REaLTabFormer(model_type="relational", parent_realtabformer_path=parent_model_path, output_max_length=1024, epochs=10)
    child_model.fit(df=child_df, in_df=parent_df, join_on=join_on, device=device)
    child_model_dir = save_dir / "rtf_child"
    child_model.save(child_model_dir)

    print(f"{sample_size} 샘플 생성")
    parent_samples = parent_model.sample(n_samples)
    parent_samples.index.name = join_on
    parent_samples = parent_samples.reset_index()

    child_samples = child_model.sample(
        input_unique_ids=parent_samples[join_on],
        input_df=parent_samples.drop(columns=[join_on]),
        gen_batch=64
    )

    print(f"{sample_size} 샘플 저장")
    parent_samples.to_csv(save_dir / f"syn_meta_{n_samples}.csv", index=False)
    child_samples_ = child_samples.reset_index().rename(columns={"index": join_on})
    child_samples_.to_csv(save_dir / f"syn_flow_{n_samples}.csv", index=False)

    syn_df = parent_samples.merge(child_samples_, on=join_on, how="inner")
    syn_df.to_csv(save_dir / f"syn_rtf_{n_samples}.csv", index=False)
    print(f"{sample_size} 완료: {save_dir}")

for size in sample_sizes:
    run_rtf(size)

5000 parent 학습
Computing the sensitivity threshold...
Using parallel computation!!!

Bootstrap round:   0%|          | 0/500 [00:00<?, ?it/s]

Sensitivity threshold summary:
count    500.000000
mean       0.000356
std        0.002593
min       -0.006570
25%       -0.001470
50%        0.000319
75%        0.002109
max        0.009229
dtype: float64
Sensitivity threshold: 0.004601478196600145 qt_max: 0.05

Map:   0%|          | 0/5000 [00:00<?, ? examples/s]

`loss_type=None` was set in the config but it is unrecognised.Using the default loss: `ForCausalLMLoss`.

  0%|          | 0/2475 [00:00<?, ?it/s]

Generated 0 invalid samples out of total 2560 samples generated. Sampling efficiency is: 100.0000%
Critic round: 5,                     sensitivity_threshold: 0.004601478196600145,                         val_sensitivity: -0.003297708795269772,                             val_sensitivities: [-0.0001958610495195866, -0.001325203252032521, -0.0028329637841832977, 0.00224020694752402, -0.0009763488543976354, -0.009313377679231337, -0.004896526237989653, -0.005304508499630451, -0.005470066518847007, -0.005446415373244642, -0.0021175166297117518, -0.0018573540280857356, -0.005304508499630452, -0.005576496674057649, -0.0010886917960088696]

There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

  0%|          | 0/2475 [00:00<?, ?it/s]

Generated 0 invalid samples out of total 2560 samples generated. Sampling efficiency is: 100.0000%
Critic round: 10,                     sensitivity_threshold: 0.004601478196600145,                         val_sensitivity: 0.0031192411924119237,                             val_sensitivities: [0.0011640798226164074, 0.0011995565410199548, 0.0009216555801921652, 0.008093865484109387, 0.006390983000739097, -0.00011308203991130897, 0.002695491500369549, 0.0017908351810790833, 0.006254988913525497, -0.00025498891352549916, 0.004741315594974131, 0.0038307464892830736, 0.0017553584626755357, 0.002080561714708056, 0.0062372505543237255]
Copying artefacts from: best-disc-model
Copying artefacts from: mean-best-disc-model
Copying artefacts from: not-best-disc-model
Copying artefacts from: last-epoch-model
5000 child 학습

Map:   0%|          | 0/104377 [00:00<?, ? examples/s]

Map:   0%|          | 0/5000 [00:00<?, ? examples/s]

Filter:   0%|          | 0/5000 [00:00<?, ? examples/s]

Map:   0%|          | 0/4819 [00:00<?, ? examples/s]

Config of the encoder: <class 'transformers.models.gpt2.modeling_gpt2.GPT2Model'> is overwritten by shared encoder config: GPT2Config {
  "activation_function": "gelu_new",
  "architectures": [
    "GPT2LMHeadModel"
  ],
  "attn_pdrop": 0.1,
  "bos_token_id": 5,
  "embd_pdrop": 0.1,
  "eos_token_id": 6,
  "initializer_range": 0.02,
  "layer_norm_epsilon": 1e-05,
  "model_type": "gpt2",
  "n_embd": 768,
  "n_head": 12,
  "n_inner": null,
  "n_layer": 6,
  "n_positions": 1024,
  "pad_token_id": 2,
  "reorder_and_upcast_attn": false,
  "resid_pdrop": 0.1,
  "scale_attn_by_inverse_layer_idx": false,
  "scale_attn_weights": true,
  "summary_activation": null,
  "summary_first_dropout": 0.1,
  "summary_proj_to_labels": true,
  "summary_type": "cls_index",
  "summary_use_proj": true,
  "torch_dtype": "float32",
  "transformers_version": "4.49.0",
  "use_cache": true,
  "vocab_size": 4982
}

Config of the decoder: <class 'transformers.models.gpt2.modeling_gpt2.GPT2LMHeadModel'> is overwritten by shared decoder config: GPT2Config {
  "activation_function": "gelu_new",
  "add_cross_attention": true,
  "attn_pdrop": 0.1,
  "bos_token_id": 5,
  "embd_pdrop": 0.1,
  "eos_token_id": 6,
  "initializer_range": 0.02,
  "layer_norm_epsilon": 1e-05,
  "model_type": "gpt2",
  "n_embd": 768,
  "n_head": 12,
  "n_inner": null,
  "n_layer": 6,
  "n_positions": 1024,
  "pad_token_id": 2,
  "reorder_and_upcast_attn": false,
  "resid_pdrop": 0.1,
  "scale_attn_by_inverse_layer_idx": false,
  "scale_attn_weights": true,
  "summary_activation": null,
  "summary_first_dropout": 0.1,
  "summary_proj_to_labels": true,
  "summary_type": "cls_index",
  "summary_use_proj": true,
  "transformers_version": "4.49.0",
  "use_cache": true,
  "vocab_size": 3431
}

5000 샘플 생성

  0%|          | 0/1000 [00:00<?, ?it/s]

Generated 0 invalid samples out of total 1024 samples generated. Sampling efficiency is: 100.0000%

Map:   0%|          | 0/1000 [00:00<?, ? examples/s]

  0%|          | 0/16 [00:00<?, ?it/s]

We strongly recommend passing in an `attention_mask` since your input_ids may be padded. See https://huggingface.co/docs/transformers/troubleshooting#incorrect-output-when-padding-tokens-arent-masked.

5000 샘플 저장
5000 완료: ../results/rtf_retail/train5000
10000 parent 학습
Computing the sensitivity threshold...
Using parallel computation!!!

Bootstrap round:   0%|          | 0/500 [00:00<?, ?it/s]

Sensitivity threshold summary:
count    500.000000
mean       0.000238
std        0.002020
min       -0.006082
25%       -0.001100
50%        0.000188
75%        0.001561
max        0.008366
dtype: float64
Sensitivity threshold: 0.0036240946045824098 qt_max: 0.05

Map:   0%|          | 0/10000 [00:00<?, ? examples/s]

  0%|          | 0/4950 [00:00<?, ?it/s]

Generated 0 invalid samples out of total 4992 samples generated. Sampling efficiency is: 100.0000%
Critic round: 5,                     sensitivity_threshold: 0.0036240946045824098,                         val_sensitivity: -0.009733185513673316,                             val_sensitivities: [-0.009564671101256467, -0.009634146341463415, -0.009131559497413157, -0.009240946045824094, -0.011838137472283813, -0.007913525498891351, -0.009335550628233553, -0.007530672579453067, -0.009634146341463415, -0.010259423503325942, -0.011122690317812269, -0.010871396895787139, -0.010719142645971914, -0.010617147080561714, -0.008584626755358461]

There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

  0%|          | 0/4950 [00:00<?, ?it/s]

Generated 0 invalid samples out of total 4992 samples generated. Sampling efficiency is: 100.0000%
Critic round: 10,                     sensitivity_threshold: 0.0036240946045824098,                         val_sensitivity: -0.0014158897383725812,                             val_sensitivities: [-0.0030753880266075374, 0.001226164079822617, 0.001847006651884701, -0.0018987435328898735, -0.0035502455582199174, 0.0005269770879526977, -0.003032520325203251, 0.0007516629711751666, -0.0024249815225424977, -0.001149297856614929, -0.0031419068736141904, -0.0008004434589800443, -0.002702882483370288, -0.002713229859571323, -0.0011005173688100507]
Copying artefacts from: best-disc-model
Copying artefacts from: mean-best-disc-model
Copying artefacts from: not-best-disc-model
Copying artefacts from: last-epoch-model
10000 child 학습

Map:   0%|          | 0/209134 [00:00<?, ? examples/s]

Map:   0%|          | 0/10000 [00:00<?, ? examples/s]

Filter:   0%|          | 0/10000 [00:00<?, ? examples/s]

Map:   0%|          | 0/9617 [00:00<?, ? examples/s]

Config of the encoder: <class 'transformers.models.gpt2.modeling_gpt2.GPT2Model'> is overwritten by shared encoder config: GPT2Config {
  "activation_function": "gelu_new",
  "architectures": [
    "GPT2LMHeadModel"
  ],
  "attn_pdrop": 0.1,
  "bos_token_id": 5,
  "embd_pdrop": 0.1,
  "eos_token_id": 6,
  "initializer_range": 0.02,
  "layer_norm_epsilon": 1e-05,
  "model_type": "gpt2",
  "n_embd": 768,
  "n_head": 12,
  "n_inner": null,
  "n_layer": 6,
  "n_positions": 1024,
  "pad_token_id": 2,
  "reorder_and_upcast_attn": false,
  "resid_pdrop": 0.1,
  "scale_attn_by_inverse_layer_idx": false,
  "scale_attn_weights": true,
  "summary_activation": null,
  "summary_first_dropout": 0.1,
  "summary_proj_to_labels": true,
  "summary_type": "cls_index",
  "summary_use_proj": true,
  "torch_dtype": "float32",
  "transformers_version": "4.49.0",
  "use_cache": true,
  "vocab_size": 9715
}

Config of the decoder: <class 'transformers.models.gpt2.modeling_gpt2.GPT2LMHeadModel'> is overwritten by shared decoder config: GPT2Config {
  "activation_function": "gelu_new",
  "add_cross_attention": true,
  "attn_pdrop": 0.1,
  "bos_token_id": 5,
  "embd_pdrop": 0.1,
  "eos_token_id": 6,
  "initializer_range": 0.02,
  "layer_norm_epsilon": 1e-05,
  "model_type": "gpt2",
  "n_embd": 768,
  "n_head": 12,
  "n_inner": null,
  "n_layer": 6,
  "n_positions": 1024,
  "pad_token_id": 2,
  "reorder_and_upcast_attn": false,
  "resid_pdrop": 0.1,
  "scale_attn_by_inverse_layer_idx": false,
  "scale_attn_weights": true,
  "summary_activation": null,
  "summary_first_dropout": 0.1,
  "summary_proj_to_labels": true,
  "summary_type": "cls_index",
  "summary_use_proj": true,
  "transformers_version": "4.49.0",
  "use_cache": true,
  "vocab_size": 3594
}

10000 샘플 생성

  0%|          | 0/1000 [00:00<?, ?it/s]

Generated 0 invalid samples out of total 1024 samples generated. Sampling efficiency is: 100.0000%

Map:   0%|          | 0/1000 [00:00<?, ? examples/s]

  0%|          | 0/16 [00:00<?, ?it/s]

10000 샘플 저장
10000 완료: ../results/rtf_retail/train10000